<!DOCTYPE html>
<html lang="es">

<head>
    <title> 3er Parcial - Diseño web </title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="estilo.css">
</head>

<header> 
    <h1 class="En">
    Diseño web - Examen tercer parcial
    </h1>

    <h2 class="En2">
    / Blog de Jose Fuertes /
    </h2>
   
    <br>    
    <button class="button-59">
            <a href="ExamenP3-Inicio.php"> Registro de articulos </a>
    </button>
    <br>
    <br>
    <hr>
</header>

<body>
    
idk

</body>
</html>

